"""Command-line interface for installer generation and publication."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from ecos_release.assemble import assemble_release_model
from ecos_release.generator import write_installer
from ecos_release.oss import store_from_env
from ecos_release.publish import (
    LATEST_HEADERS,
    VERSIONED_HEADERS,
    MemoryStore,
    PublishError,
    latest_key,
    publish_installer,
    versioned_key,
)

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_METADATA = REPO_ROOT / "metadata" / "toolchain.toml"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(prog="ecos-release")
    sub = parser.add_subparsers(dest="command", required=True)

    generate = sub.add_parser("generate", help="Generate a versioned ECC installer")
    generate.add_argument("--tag", required=True)
    generate.add_argument("--output", required=True, type=Path)
    generate.add_argument("--metadata", type=Path, default=DEFAULT_METADATA)
    generate.add_argument("--archive-dir", type=Path)
    generate.add_argument("--pdk-base-sha256")
    generate.add_argument("--pdk-liberty-file", action="append", default=[])
    generate.add_argument("--ecc-cnb-url")
    generate.add_argument("--validate-archives", action="store_true")
    generate.add_argument("--verify-cnb", action="store_true")

    plan = sub.add_parser("publish-plan", help="Print publication object keys")
    plan.add_argument("--tag", required=True)
    plan.add_argument("--installer", required=True, type=Path)

    publish = sub.add_parser("publish", help="Publish a generated installer to OSS")
    publish.add_argument("--tag", required=True)
    publish.add_argument("--installer", required=True, type=Path)

    args = parser.parse_args(argv)
    if args.command == "generate":
        model = assemble_release_model(
            args.tag,
            metadata_path=args.metadata,
            archive_dir=args.archive_dir,
            ecc_cnb_url=args.ecc_cnb_url,
            pdk_base_sha256=args.pdk_base_sha256,
            pdk_liberty_files=tuple(args.pdk_liberty_file) or None,
            validate_archives=args.validate_archives,
            verify_cnb=args.verify_cnb,
        )
        path = write_installer(model, args.output)
        print(path)
        return 0
    if args.command == "publish-plan":
        installer = args.installer.read_bytes()
        store = MemoryStore(objects={})
        result = publish_installer(store, tag=args.tag, installer=installer)
        json.dump(result, sys.stdout)
        sys.stdout.write("\n")
        return 0
    if args.command == "publish":
        installer = args.installer.read_bytes()
        store = store_from_env()
        result = publish_installer(store, tag=args.tag, installer=installer)
        _verify_anonymous(store, versioned_key(args.tag), installer, VERSIONED_HEADERS)
        if result["latest_updated"] == "true":
            _verify_anonymous(store, latest_key(), installer, LATEST_HEADERS)
        json.dump(result, sys.stdout)
        sys.stdout.write("\n")
        return 0
    return 1


def _verify_anonymous(store, key: str, expected: bytes, required: dict[str, str]) -> None:
    data, headers = store.get_anonymous(key)
    if data != expected:
        raise PublishError(f"anonymous read of {key} did not match generated bytes")
    lowered = {k.lower(): v for k, v in headers.items()}
    for name, value in required.items():
        actual = lowered.get(name.lower())
        if actual is None or value not in actual:
            raise PublishError(
                f"anonymous read of {key} has {name}={actual!r}, expected {value!r}"
            )


if __name__ == "__main__":
    raise SystemExit(main())
