"""Publication helpers for versioned and latest ECC installers."""

from __future__ import annotations

import hashlib
import json
import re
from dataclasses import dataclass
from typing import Protocol

from ecos_release.semver import InvalidVersion, Version, parse

VERSIONED_HEADERS = {
    "Content-Type": "text/x-sh",
    "Content-Disposition": "inline",
    "Cache-Control": "public, max-age=31536000, immutable",
}
LATEST_HEADERS = {
    "Content-Type": "text/x-sh",
    "Content-Disposition": "inline",
    "Cache-Control": "no-cache",
}
VERSION_ASSIGNMENT_RE = re.compile(
    r'^ECC_VERSION="([^"]+)"$',
    re.MULTILINE,
)


class PublishError(ValueError):
    """Raised when installer publication must fail closed."""


class InstallerStore(Protocol):
    def get(self, key: str) -> bytes | None: ...

    def put(self, key: str, data: bytes, headers: dict[str, str]) -> None: ...

    def put_if_absent_or_same(
        self, key: str, data: bytes, headers: dict[str, str]
    ) -> None: ...


@dataclass
class MemoryStore:
    objects: dict[str, tuple[bytes, dict[str, str]]]

    def get(self, key: str) -> bytes | None:
        item = self.objects.get(key)
        return None if item is None else item[0]

    def headers(self, key: str) -> dict[str, str] | None:
        item = self.objects.get(key)
        return None if item is None else dict(item[1])

    def get_anonymous(self, key: str) -> tuple[bytes, dict[str, str]]:
        item = self.objects.get(key)
        if item is None:
            raise PublishError(f"anonymous read of {key} failed: missing")
        return item[0], dict(item[1])

    def put(self, key: str, data: bytes, headers: dict[str, str]) -> None:
        self.objects[key] = (data, dict(headers))

    def put_if_absent_or_same(
        self, key: str, data: bytes, headers: dict[str, str]
    ) -> None:
        existing = self.objects.get(key)
        if existing is None:
            self.put(key, data, headers)
            return
        existing_data, existing_headers = existing
        if existing_data != data or existing_headers != headers:
            raise PublishError(
                f"refusing to overwrite {key} with different bytes or headers"
            )


def versioned_key(tag: str) -> str:
    return f"installers/ecc/{tag}/ecc-installer.sh"


def latest_key() -> str:
    return "installers/ecc/latest/ecc-installer.sh"


def extract_ecc_version(installer: bytes) -> str:
    text = installer.decode("utf-8")
    match = VERSION_ASSIGNMENT_RE.search(text)
    if match is None:
        raise PublishError("installer is missing ECC_VERSION assignment")
    return match.group(1)


def publish_installer(
    store: InstallerStore,
    *,
    tag: str,
    installer: bytes,
) -> dict[str, str]:
    versioned = versioned_key(tag)
    latest = latest_key()
    store.put_if_absent_or_same(versioned, installer, VERSIONED_HEADERS)
    stored = store.get(versioned)
    if stored != installer:
        raise PublishError(f"anonymous read of {versioned} did not match generated bytes")
    current_latest = store.get(latest)
    if current_latest is not None:
        try:
            current_version = parse(extract_ecc_version(current_latest))
        except (InvalidVersion, PublishError, UnicodeDecodeError) as exc:
            raise PublishError("current latest installer version assignment is malformed") from exc
        incoming = parse(extract_ecc_version(installer))
        if incoming < current_version:
            return {
                "versioned": versioned,
                "latest": latest,
                "latest_updated": "false",
                "sha256": hashlib.sha256(installer).hexdigest(),
            }
        if incoming == current_version and current_latest != installer:
            raise PublishError("latest installer bytes do not match this version")
    store.put(latest, installer, LATEST_HEADERS)
    if store.get(latest) != installer:
        raise PublishError("anonymous read of latest did not match versioned installer")
    return {
        "versioned": versioned,
        "latest": latest,
        "latest_updated": "true",
        "sha256": hashlib.sha256(installer).hexdigest(),
    }


def receipt_json(
    *,
    data_root: str,
    install_prefix: str,
    version: str,
) -> str:
    payload = {
        "binaries": ["ecc"],
        "data_root": data_root,
        "install_prefix": install_prefix,
        "provider": {"format": 1, "name": "ecos-release"},
        "version": version,
    }
    return json.dumps(payload, separators=(",", ":"), ensure_ascii=True)


def compare_versions(left: str, right: str) -> int:
    l_ver: Version = parse(left)
    r_ver: Version = parse(right)
    if l_ver < r_ver:
        return -1
    if l_ver > r_ver:
        return 1
    return 0
